### ISSUE TITLE
Failed to activate the git-commit package

### ISSUE THREAD

**Issue by fische** [alanzanattadev/atom-git-commit#1]
Hi,

I got this when I updated to 1.5.0.

**Atom Version**: 1.7.3
**System**: "Fedora release
**Thrown From**: [git-commit](https://github.com/alanzanattadev/atom-git-commit) package, v1.5.0
### Stack Trace

Failed to activate the git-commit package

```
At addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
    at invariant (/home/fische_m/.atom/packages/git-checkout/node_modules/react/node_modules/fbjs/lib/invariant.js:39:15)
    at Object.ReactOwner.addComponentAsRefTo (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactOwner.js:67:79)
    at attachRef (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactRef.js:23:16)
    at Object.ReactRef.attachRefs (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactRef.js:42:5)
    at ReactDOMComponent.attachRefs (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactReconciler.js:21:12)
    at CallbackQueue.assign.notifyAll (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/CallbackQueue.js:65:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/Transaction.js:202:25)
    at ReactReconcileTransaction.Mixin.perform (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/Transaction.js:149:16)
    at batchedMountComponentIntoNode (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactMount.js:282:15)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactUpdates.js:94:20)
    at Object.ReactMount._renderNewRootComponent (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactMount.js:476:18)
    at Object.wrapper [as _renderNewRootComponent] (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.ReactMount._renderSubtreeIntoContainer (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactMount.js:550:32)
    at Object.ReactMount.render (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactMount.js:570:23)
    at Object.wrapper [as render] (/home/fische_m/.atom/packages/git-checkout/node_modules/react/lib/ReactPerf.js:66:21)
    at Object.activate (/home/fische_m/.atom/packages/git-commit/lib/git-commit.js:28:35)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "audioBeep": false,
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-swagger",
      "raml"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "atom-material-ui",
      "atom-material-numix-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-material-numix-syntax, v0.2.1
atom-material-ui, v1.2.10
autocomplete-go, v1.0.8
bottom-dock, v0.4.4
builder-go, v1.0.0
environment, v1.2.0
git-checkout, v0.3.0
git-commit, v1.5.0
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
gulp-manager, v0.2.19
linter, v1.11.4
linter-docker, v0.1.2
linter-flake8, v1.13.0
linter-manager, v0.2.12
markdown-preview-plus, v2.4.0
merge-conflicts, v1.4.2
minimap, v4.23.2
minimap-git-diff, v4.3.0
navigator-godef, v1.0.3
tester-go, v1.0.4
todo-manager, v0.2.8

# Dev
No dev packages
```

**Comment by alanzanattadev** [comment]
Seems like many react modules are launched together, can't repro with the same versions on my laptop, any other who has the same problem ?

**Comment by edoz90** [comment]
+1

**Comment by notdodo** [comment]
**Atom Version**: 1.7.3
**System**: "Manjaro Linux"
**Thrown From**: [git-commit](https://github.com/alanzanattadev/atom-git-commit) package, v1.5.0

### Stack Trace

Failed to activate the git-commit package

```
At Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/home/dodo/.atom/packages/git-checkout/node_modules/react/node_modules/fbjs/lib/invariant.js:35:15)
    at Object.ReactOwner.addComponentAsRefTo (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/ReactOwner.js:67:373)
    at attachRef (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/ReactRef.js:23:16)
    at Object.ReactRef.attachRefs (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/ReactRef.js:42:5)
    at ReactDOMComponent.attachRefs (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/ReactReconciler.js:21:12)
    at CallbackQueue.assign.notifyAll (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/CallbackQueue.js:65:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/Transaction.js:202:25)
    at ReactReconcileTransaction.Mixin.perform (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/Transaction.js:149:16)
    at batchedMountComponentIntoNode (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/ReactMount.js:282:15)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/ReactUpdates.js:94:20)
    at Object.ReactMount._renderNewRootComponent (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/ReactMount.js:476:18)
    at Object.ReactMount._renderSubtreeIntoContainer (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/ReactMount.js:550:32)
    at Object.ReactMount.render (/home/dodo/.atom/packages/git-checkout/node_modules/react/lib/ReactMount.js:570:23)
    at Object.activate (/home/dodo/.atom/packages/git-commit/lib/git-commit.js:28:35)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.cpp": [
        "h"
      ]
    },
    "themes": [
      "dark-flat-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-beautify, v0.29.7 (inactive)
atom-save-all, v0.4.1 (inactive)
auto-detect-indentation, v1.0.0 (inactive)
autocomplete-clang, v0.9.3 (inactive)
autoupdate-packages, v1.3.1 (inactive)
build, v0.61.0 (inactive)
dark-flat-ui, v1.2.4 (inactive)
file-icons, v1.7.8 (inactive)
file-type-icons, v1.2.0 (inactive)
git-checkout, v0.3.1 (inactive)
git-commit, v1.5.0 (inactive)
glacier-syntax, v0.0.4 (inactive)
highlight-selected, v0.11.2 (inactive)
language-ini, v1.16.0 (inactive)
linter, v1.11.4 (inactive)
linter-gcc, v0.6.14 (inactive)
minimap, v4.23.2 (inactive)
minimap-highlight-selected, v4.4.0 (inactive)
monokai-seti, v0.7.0 (inactive)
notifications, v0.63.2 (inactive)
platformio-ide, v1.2.1 (inactive)
platformio-ide-terminal, v2.0.9 (inactive)
pretty-dir, v0.0.17 (inactive)
tool-bar, v0.4.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.2.0 (inactive)
one-light-ui, v1.2.0 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.0 (inactive)
solarized-light-syntax, v1.0.0 (inactive)
about, v1.4.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.0 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.29.1 (inactive)
autocomplete-snippets, v1.10.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.38.2 (inactive)
bracket-matcher, v0.81.0 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.21.0 (inactive)
find-and-replace, v0.199.0 (inactive)
fuzzy-finder, v1.0.5 (inactive)
git-diff, v1.0.1 (inactive)
go-to-line, v0.30.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.57.0 (inactive)
incompatible-packages, v0.25.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.3.1 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
notifications, v0.63.2 (inactive)
open-on-github, v1.0.1 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.235.1 (inactive)
snippets, v1.0.1 (inactive)
spell-check, v0.67.0 (inactive)
status-bar, v1.1.2 (inactive)
styleguide, v0.45.2 (inactive)
symbols-view, v0.112.0 (inactive)
tabs, v0.92.0 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.205.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.51.1 (inactive)
language-clojure, v0.20.0 (inactive)
language-coffee-script, v0.46.1 (inactive)
language-csharp, v0.12.0 (inactive)
language-css, v0.36.0 (inactive)
language-gfm, v0.85.0 (inactive)
language-git, v0.12.1 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.17.0 (inactive)
language-javascript, v0.110.0 (inactive)
language-json, v0.17.6 (inactive)
language-less, v0.29.0 (inactive)
language-make, v0.21.0 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.32.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.43.0 (inactive)
language-ruby, v0.68.3 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.46.0 (inactive)
language-shellscript, v0.21.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.20.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.27.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.4 (inactive)
language-yaml, v0.25.1 (inactive)

# Dev
No dev packages
```

**Comment by fische** [comment]
@edoz90 Start atom using the `-d` option. You will get the real error by doing that. Here it's only a minified exception, so the message doesn't give any details on what happened.

**Comment by notdodo** [comment]
@fische: running with `-d` option I got your same stack trace. Did not copy-pasted to avoid another long post: my system configs are the same of the above post.

**Comment by alanzanattadev** [comment]
React versions are collisionning by creating two instances of React which obviously leads to DOM problems .. Will fix soon, thank you for the feedbacks

**Comment by fische** [comment]
Issue fixed by updating both git-checkout and git-commit packages to, respectively, 0.3.2 and 1.5.2.
Thanks @alanzanattadev !
