### ISSUE TITLE
Failed to activate the git-commit package

### ISSUE THREAD

**Issue by luozhihua** [alanzanattadev/atom-git-commit#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.4
**Thrown From**: [git-commit](https://github.com/alanzanattadev/atom-git-commit) package, v1.5.0
### Stack Trace

Failed to activate the git-commit package

```
At Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (/Users/colin/.atom/packages/atom-mocha/node_modules/react/node_modules/fbjs/lib/invariant.js:35:15)
    at Object.ReactOwner.addComponentAsRefTo (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/ReactOwner.js:67:373)
    at attachRef (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/ReactRef.js:23:16)
    at Object.ReactRef.attachRefs (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/ReactRef.js:42:5)
    at ReactDOMComponent.attachRefs (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/ReactReconciler.js:21:12)
    at CallbackQueue.assign.notifyAll (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/CallbackQueue.js:65:22)
    at ReactReconcileTransaction.ON_DOM_READY_QUEUEING.close (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/ReactReconcileTransaction.js:81:26)
    at ReactReconcileTransaction.Mixin.closeAll (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/Transaction.js:202:25)
    at ReactReconcileTransaction.Mixin.perform (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/Transaction.js:149:16)
    at batchedMountComponentIntoNode (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/ReactMount.js:282:15)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/Transaction.js:136:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
    at Object.batchedUpdates (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/ReactUpdates.js:94:20)
    at Object.ReactMount._renderNewRootComponent (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/ReactMount.js:476:18)
    at Object.ReactMount._renderSubtreeIntoContainer (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/ReactMount.js:550:32)
    at Object.ReactMount.render (/Users/colin/.atom/packages/atom-mocha/node_modules/react/lib/ReactMount.js:570:23)
    at Object.activate (/Users/colin/.atom/packages/git-commit/lib/git-commit.js:28:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:497:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
animate-css, v0.1.4
atom-ctags, v4.5.2
atom-jade, v0.3.0
atom-less, v0.1.10
atom-math, v0.0.9
atom-mocha, v0.0.4
atomic-chrome, v0.3.0
autocomplete-ctags, v0.4.1
color-picker, v2.1.1
file-icons, v1.7.8
font-awesome-snippetset, v0.0.6
formatter-jsbeautify, v1.0.2
git-commit, v1.5.0
git-diff-details, v1.3.0
git-log, v0.4.1
git-status-utils, v0.2.0
icon-fonts, v2.5.0
javascript-snippets, v1.2.1
keyboard-localization, v1.4.18
language-babel, v2.19.3
language-javascript-jsx, v0.3.7
language-javascript-semantic, v0.2.1
linter, v1.11.4
merge-conflicts, v1.4.2
minimap, v4.23.2
minimap-git-diff, v4.3.0
pigments, v0.26.0
simplified-chinese-menu, v3.4.11
ssh-config, v0.10.1
tree-view-git-branch, v0.1.2

# Dev
No dev packages
```

**Comment by alanzanattadev** [comment]
I close this issue because it's the same that #1 :) thank you for the feedback
